# Generated by Django 4.0.4 on 2022-05-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_reservation_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='reservation',
            order_with_respect_to=None,
        ),
    ]
